#ifdef MY_BOARD
#define FIRMWARE_NAME "MY ESC "
#define FILE_NAME "MY_SEC_F421"
#define DEAD_TIME 50
#define HARDWARE_GROUP_AT_B
#define HARDWARE_GROUP_AT_045
#define VOLTAGE_ADC_CHANNEL ADC_CHANNEL_6
#define VOLTAGE_ADC_PIN GPIO_PINS_6
#endif